### ISSUE TITLE
Chrome jumps to 100% instantly

### ISSUE THREAD

**Issue by droplab** [likerRr/jq-ajax-progress#1]
Hi,

Thanks for the plugin. Noticing chrome jumps to 100% instantly when trying to upload a base64 video/image. Does this need to be converted back to a BLOB in order for the progress callback to behave as expected?

Thanks.

**Comment by likerRr** [comment]
Hi, @droplab 

I haven't noticed that before. I'll check it. Could you please provide the code that you use for it?

**Comment by likerRr** [comment]
@droplab hi, do you still experience this issue?
