### ISSUE TITLE
.progress not working

### ISSUE THREAD

**Issue by ghost** [likerRr/jq-ajax-progress#2]
``` javascript
console.log("start");

var rand = '&rand='+Math.round(new Date().getTime() / 1000);
var component_url = jQuery('#component_url').val();

jQuery.ajax(component_url+'&task=install.downloadWgiz'+rand).progress(function(e) {
    console.log("progress");
    console.log(e);
}).uploadProgress(function(e) {
    // tracking uploading
    // if (e.lengthComputable) {
    //  var percentage = Math.round((e.loaded * 100) / e.total);
    //  console.log(percentage);
});

console.log("end");
```

Thats's my code. Vars "rand" and "component_url" are working as expected. The ajax is getting called normally but i'm unable to see those two console logs inside the ".progress" function.

"console.log('start');" and "console.log('end');" are working as well.

Why?

**Comment by likerRr** [comment]
What kind of data do you try to download? Could you provide with example?
Also, what browser do you use? Do you get any errors in browser's console?
Did you try uploadProgress function? Does it work for you?
Which jQuery version do you use?

**Comment by ghost** [comment]
@likerRr, first of all, thanks for your preoccupation. After your response, i realized that other things could be causing the problem, so i decided to research. 

I found this topic http://stackoverflow.com/questions/22502943/jquery-ajax-progress-via-xhr. A user called Pilot answered the question explaining the problem.

After understand what's going on, i modified the code related to headers on my PHP download script and now i'm able to see the progress.

**Comment by likerRr** [comment]
Great :+1: thank you
