### ISSUE TITLE
jQuery UI Autocomplete issue

### ISSUE THREAD

**Issue by benscobie** [likerRr/jq-ajax-progress#4]
When this plugin is used alongside jQuery UI Autocomplete it breaks the xhr.abort() functionality inside of it.

"Uncaught TypeError: that.xhr.abort is not a function"

Relevant line in jQuery UI Autocomplete: https://github.com/jquery/jquery-ui/blob/4866e14922217560f551b86ce80952c3e0f649da/ui/widgets/autocomplete.js#L399

**Comment by likerRr** [comment]
@benscobie wow, it's interesting. I haven't used jQuery for months, so it would be great if you make a little plunker/jsfiddle where I can reproduce this error. Thank you!

**Comment by benscobie** [comment]
Thanks for replying so fast! Here's a quick and dirty jsfiddle: https://jsfiddle.net/x43ay4xL/

Start typing in the box so that it starts an AJAX request, and then type again whilst the request is still running and you'll get the JS error when it attempts to abort the current request.

**Comment by likerRr** [comment]
@benscobie hope, it's fixed. Reopen issue, if it doesn't.

**Comment by benscobie** [comment]
Still appears to be broken, updated jsfiddle: https://jsfiddle.net/x43ay4xL/2/

**Comment by likerRr** [comment]
Sorry, one file fall out of commit. Updated to 1.9

**Comment by benscobie** [comment]
Seems good now :)
