### ISSUE TITLE
Firefox stuck at 0%

### ISSUE THREAD

**Issue by kimyu-ng** [likerRr/jq-ajax-progress#5]
Have you experienced issue with `uploadProgress` callback did not get invoke at all during upload?

cc @likerRr

**Comment by likerRr** [comment]
@kimyu92 honesty, I haven't used this plugin almost since the release year ago. So I can't exactly say if it works properly in all the browsers. Do you have jsfiddle or example of the issue?

**Comment by kimyu-ng** [comment]
Chrome without this line of [patch](https://github.com/likerRr/jq-ajax-progress/blob/master/src/jq-ajax-progress.js#L46) would behave like firefox. Could it be something related to jqxhr?

However, the code below somehow fixes the issue for firefox

``` js
$.ajax({  
  xhr: function() {
    var xhr = new window.XMLHttpRequest();
    //Upload progress
    xhr.upload.addEventListener("progress", function(evt){
      if (evt.lengthComputable) {
        var percentComplete = evt.loaded / evt.total;
        //Do something with upload progress
        console.log(percentComplete);
      }
    }, false);
    //Download progress
    xhr.addEventListener("progress", function(evt){
      if (evt.lengthComputable) {
        var percentComplete = evt.loaded / evt.total;
        //Do something with download progress
        console.log(percentComplete);
      }
    }, false);
    return xhr;
  },
})
.uploadProgress(function(event) {
  // get invoked
})
```

**Comment by likerRr** [comment]
@kimyu92 I'll take a look, thank you for the help. I can't say what causes a problem. Is it only a firefox related only? Have you checked IE, Edge, Safari, Opera?

**Comment by kimyu-ng** [comment]
afaik chrome and firefox will not work if you also take out the chrome patch.

**Comment by likerRr** [comment]
@kimyu92 is it still actual?

**Comment by likerRr** [comment]
Discussing continues here #7
