### ISSUE TITLE
Browserify support?

### ISSUE THREAD

**Issue by maxpaj** [likerRr/jq-ajax-progress#6]
Hi, sorry if this is the wrong forum for this - but how do you use this with browserify? 

I've tried just require()-ing the module right after my jQuery is loaded, but it doesn't add the methods to promises created through $.ajax()

```
var $	 = require('jquery');
window.$ = window.jQuery = $;
require('jq-ajax-progress');
```

Then I set up the $.ajax as usual:
```
var promise = $.ajax({
    url: getApiUri(),
    type: 'POST',
    ...
});
```

But then `promise.uploadProgress is not a function` when I want to pass a function to it. Indeed if I inspect the promise, it has no function called `uploadProgress`. But I can see that the code is ran where it replaces the "old" `$.ajax`.

**Comment by likerRr** [comment]
Sorry, not yet

**Comment by likerRr** [comment]
@maxpaj 
Library was updated to the version [1.0.0](https://github.com/likerRr/jq-ajax-progress/releases/tag/v1.0.0), please try it. 

I also checked browserify support and it works for me. You have to manually add `jquery` to your project and then repeat the same actions as you did before, but with a new API:

```js
var $	 = require('jquery');
window.$ = window.jQuery = $;
require('jq-ajax-progress');

var jqxhr = $.ajax({
    type: 'POST',
    url: 'http://null.jsbin.com/upload',
    data: formData,
    cache: false,
    contentType: false,
    processData: false,
    success: function(data) {
      console.log(data);
    },
    error: function(data) {
      console.log(data);
    },
    progress: downloadProgress,
    uploadProgress: uploadProgress
  });
```

Then build it with browserify and add built script to your page. Please, re-open issue if you still experience the same problem
