### ISSUE TITLE
[Android - Firefox] uploadProgress() callback not fired ..

### ISSUE THREAD

**Issue by marmz** [likerRr/jq-ajax-progress#7]
Hi.
I have been using your plugin on my latest projects, and it always worked fine ...
well... **almost** always :S

I _never_ had problems on most common **desktop browsers**.
Also on **Chrome (x Android)** seems to work **fine**.

But i just discovered that, on **Firefox (x Android)**, the `uploadProgress()` callback is **NEVER executed**! 

I hope this project is still mantained and issues checked ;))
Anyway, thanks for your job!

**Comment by likerRr** [comment]
Hi! 
Can you please provide **Android** and **Firefox** versions where you found the issue? 
Probably you can also provide a simple example code which clearly shows the issue?

**Comment by marmz** [comment]
Sure!
- Android **6.0.1** (Marshmallow)
- Firefox **56.0**

Example (pseudo-code):
```
$.ajax(...).uploadProgress( function(e) {
    console.log(e);
});
```

Try this, and you'll see that it doesn't "print" anything...
So, the callback is never triggered, but no errors are thrown ......

**Comment by likerRr** [comment]
@marmz can you please check this example http://jsbin.com/nayimukiza/1/edit?js,console,output on mobile? I've tested on Adnroid 6.0 with Firefox 56 and it works fine.

Please, compare it with your usage and say what do you do differently

**Comment by marmz** [comment]
@likerRr 
well.. i tried you code on **Firefox stable** and also on **Firefox nightly**, but i only get the "final" alert

> data returned successfully

that was triggered by $.ajax "success" callback...
but nothing else..

On **Chrome (Android)** and **main Desktop** Browsers, all is fine, i repeat ....  **:(**
Could this depend on device architecture? I am using an ASUS Zenfone 2, which runs **x86_64** 

I'll try soon with a different device.. and let ya know!

**Comment by likerRr** [comment]
Hm, it's strange. I tested it on yesterday on **Xiaomi Redmi Note 4** and it worked but now it stopped work. Let me do further investigation.

**Comment by likerRr** [comment]
I've investigated the issue and I totally dislike the architecture as it is right now. Seems like when you call `upload` or `uploadProgress` methods, **xhr** instance has already been [initialized](https://github.com/likerRr/jq-ajax-progress/blob/master/src/jq-ajax-progress.js#L48) and request is sent. And honestly I think it's a miracle that library sometimes works at all :) I will rewrite the core and future usage will look like this:

```javascript
$.ajax(url, {
    progress(e => {
      // tracking downloading
      // if (e.lengthComputable) {
      //  var percentage = Math.round((e.loaded * 100) / e.total);
      //  console.log(percentage);
      //}
    }),
    uploadProgress(e => {
      // tracking uploading
      // if (e.lengthComputable) {
      //  var percentage = Math.round((e.loaded * 100) / e.total);
      //  console.log(percentage);
      //}
    })
});
```
I made locally some tests and new code seems working. So, be patient and wait for release `1.0.0`

**Comment by marmz** [comment]
Well, honestly i loved the current implementation, because i could use "chainable" callbacks on **$jqxhr**  object...
Anyway, thanks for helping.
May the force be with you! :D

**Comment by marmz** [comment]
Hi again!
I'd like to share with you another possible implementation i found here on GitHub:
[cvelazquez/jquery.ajax.progress](https://github.com/cvelazquez/jquery.ajax.progress)

It uses `$.on()` events/triggers.

I did not try this yet. Maybe it could be of inspiration (or maybe not.. dunno..)
Bye :D

**Comment by likerRr** [comment]
Thank you for sharing!
I don't like the idea that this library always adds event listeners on progress events even when you don't need them. That's why I want to move progress/upload callbacks to options

**Comment by kimyu-ng** [comment]
I agree with @marmz, chainable callbacks are preferable.
@likerRr any progress on rewriting it?

**Comment by marmz** [comment]
Hi man. 
Passed by just to ask you if there are any chances for a new release ..... Peace!

**Comment by marmz** [comment]
Hi man. 
Passed by just to ask you if there are any chances for a new release ..... Peace!

**Comment by marmz** [comment]
Hi man. 
Passed by just to ask you if there are any chances for a new release ..... Peace!

**Comment by likerRr** [comment]
@kimyu92 @marmz sorry guys for late response. I'll deal with that till the end of week. Thanks for waiting

**Comment by marmz** [comment]
Cant wait, man! :grinning:

**Comment by likerRr** [comment]
@marmz , @kimyu92 hey guys! Please, check a new version (p.s. look at [release notes](https://github.com/likerRr/jq-ajax-progress/releases/tag/v1.0.0), because api has changed). Feel free to open new issues
